name: Run integration tests with the official doc suite
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
jobs:
  build-base-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: antoniogamiz/documentable-testing
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: testing.Dockerfile
          tags: "latest"
  build-documentable-container:
    needs: build-base-container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: antoniogamiz/documentable-nightly
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: production.Dockerfile
          buildargs: branch_name=develop
          tags: "latest"
  build-documentation:
    needs: build-documentable-container
    runs-on: ubuntu-latest
    container: antoniogamiz/documentable-nightly
    steps:
      - uses: actions/checkout@master
      - run: |
          documentable setup -o
          documentable start --topdir=docs -v -a --highlight --highlight-path="/highlights"
        name: Generate docs
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.5.7
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: html
          SINGLE_COMMIT: true
          CLEAN: true
          COMMIT_MESSAGE: "[skip ci]"
  build-official-doc:
    needs: build-documentable-container
    runs-on: ubuntu-latest
    container: antoniogamiz/documentable-nightly
    steps:
      - run: |
          git clone -b master --single-branch https://github.com/Raku/doc.git
          cd doc
          documentable setup -o
          rm documentable.json && rm type-graph.txt
          wget https://raw.githubusercontent.com/Raku/doc/master/type-graph.txt
          wget https://raw.githubusercontent.com/Raku/Documentable/docs-assets/documentable.json
          documentable start -a -v
      - uses: actions/checkout@master
      - name: Deploy official doc set  ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.5.7
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: html
          TARGET_FOLDER: integration-test
          SINGLE_COMMIT: true
          COMMIT_MESSAGE: "[skip ci]"
          DEBUG: true
